### ISSUE TITLE
help with adding a feature to the plugin

### ISSUE THREAD

**Issue by 420Spawn** [qgist/workbench#12]
**This is not an issue per say.. more of a suggestion for improvement and help with applying it**
Hello, as part of an assignment I reviewed your plugin and gave it a suggestion to be able to change the different toolbar/widgets colors to be able to have more customizability to the different profiles and to separate different functions within the same profile by color.
I was told that it was a good suggestion and was asked to implement this feature.
I was wondering if it was possible to get your teams help since I'm not very familiar with GUI coding and I think this is something that really can improve this plugin.
I was also wondering why is the plugin still considered as experimental without newer stable versions after such a long time since the last published version.

**Comment by s-m-e** [comment]
Hi @420Spawn, first of all welcome! We can certainly help with that and the idea sounds nice, yes. Your suggested change should be relatively easy to implement. You probably have to do two things:

1) Figure out how the user configures the color(s). See [manager UI definition](https://github.com/qgist/workbench/blob/master/qgist/workbench/ui_manager_base.py), [manager UI logic](https://github.com/qgist/workbench/blob/master/qgist/workbench/ui_manager.py) and the [central configuration](https://github.com/qgist/workbench/blob/master/qgist/config.py).
2) Apply the color to the user interface element(s) in question. See [UI element representation](https://github.com/qgist/workbench/blob/master/qgist/workbench/dtype_uielement.py).

This project uses [PyQt5](https://www.riverbankcomputing.com/static/Docs/PyQt5/), a Python wrapper around [Qt5](https://doc.qt.io/qt-5/).

Experimental: Technically, it works, but the plugin does not see as much regular testing as it should. Implementing automatic CI tests for GUI code is not trivial at all, so we're stuck with manual tests across a bunch of QGIS versions whenever time permits. It is certainly possible to remove the "experimental" label, but this would imply some sort of regular testing strategy.
